INSERT INTO `skp8s_trsproperties_field` VALUES
(100,'field_title',8,'text','Property Title',1,1,'Property title'),
(101,'field_summary',8,'textarea','Summary Description',7,1,'Short property description'),
(102,'field_postal_code',8,'text','Postal Code',4,1,'Property postal code'),
(103,'field_street',8,'text','Address',3,1,'Property address'),
(104,'field_price',8,'text','Price',5,1,'Price'),
(105,'field_bedrooms',8,'text','Bedrooms',10,1,'Property bedrooms number'),
(106,'field_bathrooms',8,'text','Bathrooms',10,1,'Property bathroom number'),
(107,'field_contact_person',8,'text','Contact Person',7,1,'Property contact person'),
(108,'field_phone_number',8,'text','Contact Phone Number',7,1,'Phone number for the contact person for the property'),
(109,'field_sqft',8,'text','Square Feet',15,1,'Square feet size of the property'),
(110,'field_plot_area',8,'text','Plot Area',9,1,'Property plot area'),
(111,'field_year_of_completion',8,'text','Year of Completion',1,1,'Property year of completion'),
(112,'field_features',8,'textarea','Features',9,1,'Property features'),
(113,'field_heating_and_cooling',8,'text','Heating and Cooling',2,1,'Heating and Cooling information'),
(114,'field_gallery',8,'gallery','Images',13,1,'Property images'),
(115,'field_description',8,'textarea','Description',2,1,'Long property description'),
(116,'field_special_offer',8,'text','Special Offer',15,1,''),
(117,'field_website',8,'text','Website',16,0,''),
(118,'field_special',8,'text','Special',17,1,''),
(119,'field_type',8,'text','Type',18,1,''),
(120,'field_design',8,'text','Design',19,1,''),
(121,'field_floor_no',8,'text','Floor',20,1,''),
(122,'field_app_fee',8,'text','Fee',3,1,''),
(123,'field_date_available',8,'text','Date Available',11,1,''),
(124,'field_second_deposit',8,'text','Security Deposit',23,1,''),
(125,'field_min_term',8,'text','Minimum Term',24,1,''),
(126,'field_parking',8,'text','Parking',12,1,''),
(127,'field_basement',8,'text','Basement',25,1,''),
(128,'field_other',8,'textarea','Other',25,1,'Other information about the property'),
(129,'field_remarks',8,'textarea','Remarks',8,1,'Remarks about the property'),
(130,'field_furnished',8,'text','Furnished',13,1,''),
(131,'field_pets',8,'text','Pets Allowed',14,1,'Information about pets'),
(133,'field_apply_at',8,'text','Apply At',30,1,''),
(134,'field_country',8,'text','Country',6,1,''),
(135,'field_city',8,'text','City',5,1,''),
(136,'field_location',8,'text','Location',3,1,'Property location'),
(137,'field_mls_no',8,'text','MLS Number',33,1,''),
(138,'field_property_type',8,'radio','Property Type',0,0,'Property Type'),
(139,'field_laundry',8,'radio','Laundry',1,0,'Laundry');
